name: ecommerce_analytics_pipeline
version: 1.0.0
config-version: 2

profile: ecommerce_analytics_pipeline

model-paths:
  - models
seed-paths:
  - seeds

analysis-paths:
  - analyses
macro-paths:
  - macros
snapshot-paths:
  - snapshots

clean-targets:
  - target
  - dbt_packages

vars:
  raw_data_path: "./data-sources/online-retail.csv"

models:
  ecommerce_analytics_pipeline:
    bronze:
      +materialized: table
    silver:
      +materialized: table
    gold:
      +materialized: table
