version: 2

sources: []

models:
  - name: bronze_online_retail
    description: Raw ingestion of the Online Retail CSV.
    columns:
      - name: invoice_no
        tests:
          - not_null

  - name: silver_online_retail
    description: Cleaned and typed transactions with derived metrics.
    columns:
      - name: invoice_no
        tests:
          - not_null
      - name: invoice_ts
        tests:
          - not_null

  - name: gold_sales_daily
    description: Daily sales rollup.
    columns:
      - name: sales_date
        tests:
          - not_null

  - name: gold_customer_metrics
    description: Customer-level KPIs.
    columns:
      - name: customer_id
        tests:
          - not_null
